spring:
 profiles.active: development
 jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy 
spring.data.jpa.repositories.enabled: true

security:
  basic:
    enabled: false

spring.jpa:
    show-sql: true
    format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
 profiles: development
parking.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/carparking
  username: ${IVP_ORCH_DB_USERID:root}
  password: ${IVP_ORCH_DB_PASSWD:viki}
  accessToUnderlyingConnectionAllowed: true
  max-active: 25
  max-idle: 10
  min-idle: 1
  initial-size: 1
  validation-query: "SELECT 1"
  test-on-borrow: true
---
server:
  port: 8888